In [1]:
import numpy as np
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [2]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a3 = np.array(
    [[[1,2,3],
      [3,4,5]],
     [[1,2,3],
      [4,5,6]
      ]])
a3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [3]:
a3.shape

(2, 2, 3)

In [4]:
a1.ndim

1

In [5]:
a3.size

12

In [6]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2.  Creating array

In [7]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [8]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:

zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [11]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[3, 1, 3, 4, 2],
       [3, 9, 6, 9, 8],
       [7, 0, 4, 9, 5]])

In [12]:
random_array.size

15

In [13]:
random_array.shape

(3, 5)

In [14]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.89076964, 0.45102439, 0.15445217],
       [0.43158245, 0.60590206, 0.57181642],
       [0.65110094, 0.25971449, 0.67091218],
       [0.35849336, 0.1338954 , 0.25831017],
       [0.76784794, 0.9608877 , 0.53484177]])

In [17]:
rand_ar_3 = np.random.randint(10, size=(5,3))
rand_ar_3

array([[9, 9, 2],
       [6, 4, 3],
       [8, 5, 1],
       [9, 3, 9],
       [8, 7, 3]])

# creo un arrai massivo

In [18]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [20]:
# numpy sarà più veloce (timeit mostra il tempo impiegato per fare quella cosa)
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumpySum§

5.88 ms ± 81.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
20.8 µs ± 1.7 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
