In [1]:
import numpy as np
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [6]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a3 = np.array(
    [[[1,2,3],
      [3,4,5]],
     [[1,2,3],
      [4,5,6]
      ]])
a3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
a3.shape

(2, 2, 3)

In [8]:
a1.ndim

1

In [10]:
a3.size

12

In [11]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2.  Creating array

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:

zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[5, 7, 5, 8, 6],
       [0, 9, 7, 0, 9],
       [4, 3, 0, 7, 2]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.28204171, 0.2204635 , 0.76720901],
       [0.76826368, 0.03485271, 0.08049933],
       [0.02632315, 0.76599477, 0.41209644],
       [0.25385117, 0.94921094, 0.64828853],
       [0.07251853, 0.09586063, 0.09415168]])